### PR TITLE
Add structure for the game

### PR DESCRIPTION
**Pull request by ammarkandel**
Build user_interface for the game. get player input and check if it valid then displays the structure of the board and add the initialize method.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
### Status: Invalid Code Review Request :x: 

__Hi team, I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reasons:__

- [x] You did not work with Git Flow in your repository. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOPhttps://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/gitflow.png/gitflow.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- You did not have the production (main) branch in this repository.
- You should have your production (main) branch + the development branch, then make pull requests from feature branches (i.e. user_interface) to the development branch.

Friendly reminder: You should use Git Flow in this project.
Please take a step back and read [this pathwright lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/). Then create a brand new repo with the correct setup and feature branch (with DESCRIPTIVE name) and copy your code there or close this pull request and create another one with the correct feature branch.
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

* * *

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [x] At the end of your main.rb file, you have an extra **end** tag. Please remove that tag. That tag is stopping the file to execute. 
## Behaviour

- [x] In this step you are supposed to only **mock** the basic flow of the game. This means implementing a user interface that displays prompts for users (print/puts) and collects user input (`gets.chomp`). No game logic (for example checking who is a winner) is required in this milestone - instead, you can just display "The winner is X" no matter who won. Usage of inline comments in this milestone is allowed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
- [x] Basic game flow is prepared: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- [x] [OPTIONAL] game asks players for their names  

- [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
- [x] `[REQUIRED]` game asks the player to select from available moves
- [x] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
- [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
- [x] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
- [x] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
- [x] `[REQUIRED]` game repeats all actions for the next player's move

  **But your game gives an error after the first move**

## Implementation details

- [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
- [ ] Inside the loop, you should call actions repeated for each move
- [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
 game_on = false
  end
end
```

- [ ] Using out-of-nowhere numbers to terminate a loop, for example, `5.times do ... end` is a signal that something is wrong. Advise usage of terminating variable as above.




**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @ammarkandel :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

**Behaviour**
  * [x] game tells which player turn it is (without computing who the winner is)
  
   - [x] game asks the player to select from available moves
  
  - [x] game informs player if the selected move is invalid (without computing what an invalid move is)
  
  - [x] game displays board after the player move (without computing which spots on the board are taken)
  
  - [x] game informs player if the selected move is a winning move (without computing the winning move)
  
  - [x] game informs player if the selected move is a draw move (without computing draw)
  
  - [x] game repeats all actions for the next player's move

### Please, make the requested changes and submit for another review.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @ammarkandel  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] You have removed this line of code `#!/usr/bin/env ruby` which wask making your `bin/main` file to be executable hence it's no longer executable, please add it back
- [x] The game should display a proper board, currently it's displaying
 ||   || 
 ||   || 
 ||   || which is not a board
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by javitocor — APPROVED** [review]
# STATUS APPROVED 🌟 

Congratulations team! 👍 
Project approved! 🥳 
All your hard work has brought you here, ready to work in the next milestone! 🚀 
Remember to fill up the completion form 📑  merge the branch and you can start working in the next one!
Good luck with it! 😺

**Pull request merged**
