### PR TITLE
Setup files for milestone 1: Project setup

### PR DESCRIPTION
**Pull request by ammarkandel**
Setup project : 
                         - Linter files and rubcop
                         - The main ruby file in the bin folder

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @ammarkandel . Thanks for submitting you project!

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [x] PR message has no information or description, please edit it to add something related to the setup milestone.
- [x] `# frozen_string_literal: true` is not needed please remove it from the file.
- [x] GitHub actions / Linters are not set up correctly. Please fix this before submitting the project for a rereview.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 
Hello team! Thanks for making the requested changes. Your linters are here, and your PR has a meaningful name. :+1: However, before moving forward there are some things that need to be taken care of.

- [x]  I am not sure on your end, because your main.rb has '# !/usr/bin/env ruby' but I can't run your app without calling ruby. But it needs to be an executable file. For more information check [here](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/). If it is already an executable on your end, please refer [here](https://git-scm.com/docs/git-update-index).
update-file-permissions

You've arranged lib and bin folders, and after you make the main file as an executable, I believe you are good to go. :100: 
If you have any questions about the review, please reach me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @ammarkandel  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] The `bin/main.rb` file is still not executable. Please kindly folloe [this tutorial](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/) and know how to make a ruby file executable. Then apply it to `bin/main.rb` file
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by ammarkandel** [comment]
hi @descholar-ceo descholar-ceo
I tried to make the file executable and when I run this command         ls -l main.rb    give me that it is executable  (   -rwxr-xr-x 1 nvidia nvidia 41 ينا  5 23:33 main.rb   )

**Comment by ammarkandel** [comment]
also, I tried all commands and when test give me this command not found

**Comment by ammarkandel** [comment]
hi @descholar-ceo 

When run the file give me puts command not found.

**Comment by ammarkandel** [comment]
so the file execute but give me an error (             in line two puts command not found                        )

**Comment by ammarkandel** [comment]
I fixed the executable file

**Review by Srjnnnn — APPROVED** [review]
## Status: Approved :tada: :partying_face: 
Hello team. We're in contact and it is great to see that you've solved the making the file executable issue.

You can merge and move forward. :+1: 
_Eyüp Sercan UYGUR_

**Pull request merged**
